version: "3.8"
services:
  processing_service:
    env_file:
      - .env
    volumes: []  # Pas de montage - code dans l'image seule
    ports:
      - "${PORT}:${PORT}" # seulement à l'intérieur du réseau Docker "${PORT}"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
