version: "3.8"

services:
  processing_service:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}" # seulement à l'intérieur du réseau Docker "${PORT}"
    volumes:
      - ./src:/app/src                # Monte uniquement le dossier src (code source)
      - /app/node_modules            # Volume anonyme pour node_modules dans le conteneur
      - ./tsconfig.json:/app/tsconfig.json:ro  # Monter tsconfig pour dev TypeScript (en lecture seule)
      - ./package.json:/app/package.json:ro    # Monter package.json seul, si vraiment nécessaire (parfois pas utile)
    command: npx nodemon --watch src --ext ts,json --exec ts-node src/index.ts