version: "3.8"
services:
  processing_service:
    build:
      args:
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT}
    volumes: [] # Pas de montage - code dans l'image seule
    ports:
      - "${PORT}:${PORT}" # seulement à l'intérieur du réseau Docker "${PORT}"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    command: node dist/index.js
  cassandra:
    container_name: cassandra
